In [3]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [5]:
effective_rivers = pd.read_csv("./good_rivers.csv")
effective_rivers

,segmentID,segmentInd,Name,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,1,3758,Kansas River,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3943,Kansas River,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,4137,Kansas River,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4310,Kansas River,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,4501,Kansas River,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,167,16220,Missou at culbertson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
769,167,16706,Missou at culbertson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
770,167,17181,Missou at culbertson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771,167,17658,Missou at culbertson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
772,167,18609,Missou at culbertson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
cs_all = gpd.read_file("./intersected_validation.shp")
cs_all

,OBJECTID_1,FID_usBasi,oldReachID,area,reachID,FID_63_val,OBJECTID,Join_Count,TARGET_FID,OID_,...,Gauge_no,ID,lat_dd,lon_dd,width_m,xDir,segDist_m,segmentID,segmentInd,geometry
0,1,0,10.0,1.345455e+06,58.0,59,60,1,857,858,...,6926000,437,38.191367,-92.609507,175.0,281.552431,130513.0,11.0,3759,POINT Z (-92.60741 38.19142 6926000.00000)
1,2,1,19.0,1.336048e+06,57.0,59,60,1,857,858,...,6926000,437,38.191367,-92.609507,175.0,281.552431,130513.0,11.0,3759,POINT Z (-92.60741 38.19142 6926000.00000)
2,3,56,11.0,3.898778e+04,2.0,59,60,1,857,858,...,6926000,437,38.191367,-92.609507,175.0,281.552431,130513.0,11.0,3759,POINT Z (-92.60741 38.19142 6926000.00000)
3,4,0,10.0,1.345455e+06,58.0,60,61,1,858,859,...,6926510,416,38.423244,-92.212691,117.0,305.482387,55410.0,11.0,1608,POINT Z (-92.20825 38.42144 6926510.00000)
4,5,1,19.0,1.336048e+06,57.0,60,61,1,858,859,...,6926510,416,38.423244,-92.212691,117.0,305.482387,55410.0,11.0,1608,POINT Z (-92.20825 38.42144 6926510.00000)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,989,19,119.0,4.355455e+05,39.0,13,14,11,91,92,...,6132000,6725,48.047417,-106.336909,399.0,209.970588,1650.0,169.0,47,POINT Z (-106.35626 48.04443 6132000.00000)
989,990,20,123.0,4.338981e+05,38.0,13,14,11,91,92,...,6132000,6725,48.047417,-106.336909,399.0,209.970588,1650.0,169.0,47,POINT Z (-106.35626 48.04443 6132000.00000)
990,991,21,122.0,4.282865e+05,37.0,13,14,11,91,92,...,6132000,6725,48.047417,-106.336909,399.0,209.970588,1650.0,169.0,47,POINT Z (-106.35626 48.04443 6132000.00000)
991,992,22,121.0,4.244440e+05,36.0,13,14,11,91,92,...,6132000,6725,48.047417,-106.336909,399.0,209.970588,1650.0,169.0,47,POINT Z (-106.35626 48.04443 6132000.00000)
992,993,23,169.0,1.483447e+05,35.0,13,14,11,91,92,...,6132000,6725,48.047417,-106.336909,399.0,209.970588,1650.0,169.0,47,POINT Z (-106.35626 48.04443 6132000.00000)